### ISSUE TITLE
[Question] How to stop sharing?

### ISSUE THREAD

**Issue by e-t-l** [VentralDigital/InterProfileSharing#6]
After sharing a file from one profile, is there a way to *stop* the sharing / make the shared file inaccessible / kill the sharing service?

**Comment by e-t-l** [comment]
Yes, thank you! I must have missed the Stop Sharing button. I was using it to transfer files from Owner to Work profile, so both notifications were on the same screen.

From your instructions, it also sounds like only one thing can be shared from one profile at a time?

**Comment by patrickd-** [comment]
You can share multiple things at once but only from one profile at a time.

The profile that shares something starts the SharingService that acts like a Server, while the other instances of the app running in other profiles detect that a Server is running and then act like a Client. By sharing something the app basically switches from Client-mode to Server-mode.

**Comment by patrickd-** [comment]
Updated readme to include more prominent information on stopping the sharing service. Closing
